version: "3.7"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    container_name: covid19-elasticsearch-single
    environment:
      - node.name=covid19-elasticsearch-single
      - cluster.name=covid19-elasticsearch-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - covid19-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - covid19-network

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    container_name: covid19-kibana
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: covid19-kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - covid19-network
  
  sauron:
    build: 
      dockerfile: ./sauron/sauron.dockerfile
      context: ./
    image: covid-19-monitor/sauron:latest
    container_name: sauron
    environment: 
      Logging__LogLevel__Hangfire: Information
      ElasticsearchApiBaseAddress: http://elasticsearch:9200
      Covid19DataApiBaseAddress: https://brasil.io/api/dataset/covid19/
    ports:
      - 8081:80
      - 8143:443
    depends_on: 
      - elasticsearch
    networks:
      - covid19-network
      
volumes:

  covid19-postgres-data:
    name: covid19-postgres-data
    driver: local

  covid19-elasticsearch-data:
    name: covid19-elasticsearch-data
    driver: local     

networks:
  covid19-network:
    driver: bridge
    name: covid19-network
    